sudo: false
language: python
python:
  - "3.4"
  - "3.5"
services:
  - redis-server
  - postgresql
install:
  - pip install -U pip
  - pip install -r requirements/test.txt
  - pip freeze
cache:
  directories:
    - $HOME/.cache/pip
    - bower_components/
    - node_modules/
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
  - bower install
  - node_modules/.bin/grunt build
script: py.test --cov=./
after_success:
  - codecov
env:
 - DATABASE_URL=postgres://postgres@127.0.0.1:5432/travis_ci_test DJANGO_SETTINGS_MODULE=config.settings.local DJANGO_ALLOWED_HOSTS=127.0.0.1 DJANGO_SECURE_SSL_REDIRECT=False SOCIALHOME_DOMAIN=127.0.0.1:8000 SOCIALHOME_HTTPS=False DJANGO_DEBUG=False DJANGO_DEBUG_TOOLBAR=False
