version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../traefik/traefik.toml:/traefik.toml
      - ./../traefik/acme.json:/acme.json

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis

  app:
    container_name: socialhome
    image: jaywink/socialhome
    restart: unless-stopped
    depends_on:
      - redis
#      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "23564:23564"
    volumes:
      - media:/app/socialhome/media
    labels:
      traefik.frontend.rule: "Host:demo.socialhome.network"
      traefik.port: "5000"
      traefik.enable: "true"

#  db:
#    container_name: db
#    image: postgres
#    restart: unless-stopped

volumes:
  media:
